---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: dist.zip
    dest: ~/backend_app/dist.zip

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app
    unzip dist.zip
    rm -rf dist.zip
- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm install

- name: "Start backend with pm2"
  become: true
  command: pm2 start npm -- run start

- name: "print message"
  debug:
    msg: "{{ execute_node.stdout_lines }}"
