---
# - name: "show remote environment"
#   shell: env
# - name: "Creates backend app directory"
  # file:
  #   path: /home/ubuntu/uda_app
  #   state: directory

# - name: "Copy compiled backend app"
#   copy:
#     src: dist.zip
#     dest: /home/ubuntu/backend


- name: Copy backend files
  become: true
  copy:
    src: dist.zip
    dest: /home/ubuntu
- name: Unzip backend files to correct directory
  shell: |
    cd /home/ubuntu/
    unzip dist.zip
    rm -rf dist.zip

# - name: "copy backend binaries"
#   become: yes
#   copy:
#     src: dist
#     dest: /home/ubuntu/uda_app
- name: Install Node Modules
  shell: |
    cd /home/ubuntu
    sudo npm install
    
# - name: Building Node Service
#   shell: |
#     cd /home/ubuntu
#     sudo npm run build
#     sudo npm run prestart:prod

- name: Start PM2
  shell: |
    cd /home/ubuntu
    pm2 start npm -- run start:prod


# - name: "copy node_modules"
#   become: yes
#   synchronize:
#     src: ../../backend/node_modules
#     dest: /home/ubuntu/uda_app
#     recursive: true
# - name: "copy backend file"
#   become: true
#   copy:
#     src: ~/project/.circleci/project/backend/dist
#     dest: /home/ubuntu/backend
# - name: Start PM2
#   shell: |
#     cd /home/ubuntu/
#     tar xzvf backend.tar.gz
#     mv home/circleci/project/backend .
#     cd backend
#     sudo npm install -g npm@latest
#     sudo npm install -g webpack-dev-server
#     sudo npm install
#     sudo npm run build
#     sudo pm2 start npm --name backend -- start:prod




# - name: "Install dependencies for project"
#   shell: |
#     cd /home/ubuntu/backend
#     npm install
# - name: "install npm packages"
#   become: true
#   command: npm install
#   args:
#     chdir: ~/backend
# - name: "compile npm packages"
#   become: true
#   command: npm run build
#   args:
#     chdir: ~/backend
# - name: "compile npm packages"
#   shell: |
#     cd /home/ubuntu/backend
#     npm run build

# - name: "start server"
#   become: true
#   command: pm2 start npm -- run start
#   args:
#     chdir: ~/backend/dist
# - name: "delete anything that might already be running"
#   become: true
#   command: pm2 delete all
#   ignore_errors: true

# - name: "start server"
#   become: true
#   command: pm2 start -f ./main.js
#   args:
#     chdir: /home/ubuntu/uda_app/dist

# - name: "Start PM2"
#     shell: |
#       cd /home/ubuntu/backend
#       sudo npm install -g npm@latest
#       sudo npm install -g webpack-dev-server
#       sudo npm install
#       sudo npm run build
#       pm2 start npm -- run start:prod

# - name: "Start backend with pm2"
#   become: true
#   command: |
#     cd ~/backend && pm2 start npm --name backend -- start

# - name: "print message"
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"
